// src/app/components/item-edit-modal/item-edit-modal.component.ts
import { Component, input, OnInit, ViewChild } from '@angular/core';
import {
  FormControl,
  FormGroup,
  FormsModule,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import {
  IonButton,
  IonButtons,
  IonContent,
  IonHeader,
  IonInput,
  IonItem,
  IonModal,
  IonTitle,
  IonToolbar,
} from '@ionic/angular/standalone';
import { StoreService } from '@store/services/store.service';
import { ReceiptItem } from '@store/states/receipt.state';

@Component({
  imports: [
    IonButton,
    FormsModule,
    IonInput,
    IonItem,
    IonModal,
    IonHeader,
    IonToolbar,
    IonButtons,
    IonTitle,
    IonContent,
    ReactiveFormsModule,
  ],
  selector: 'app-item-edit-modal',
  standalone: true,
  styleUrls: ['./item-edit-modal.component.scss'],
  templateUrl: './item-edit-modal.component.html',
})
export class ItemEditModalComponent implements OnInit {
  currencyCode = input<string>('');
  itemData = input<ReceiptItem>();
  itemForm = new FormGroup({
    description: new FormControl<string>('', {
      nonNullable: false,
      validators: [],
    }),
    name: new FormControl<string>('', {
      nonNullable: true,
      validators: [],
    }),
    quantity: new FormControl<number>(1, {
      nonNullable: true,
      validators: [Validators.required, Validators.min(1)],
    }),
    unitPrice: new FormControl<number>(0, {
      nonNullable: true,
      validators: [Validators.required, Validators.min(0)],
    }),
  });
  @ViewChild(IonModal) modal!: IonModal;

  name = 'something';

  triggerId = input<string>('');

  constructor(private storeService: StoreService) {}

  cancel() {
    this.modal.dismiss();
  }

  confirm() {
    this.modal.dismiss(this.name, 'confirm');
  }

  ngOnInit() {
    this.itemForm.patchValue({
      description: this.itemData()?.description || '',
      name: this.itemData()?.name || '',
      quantity: this.itemData()?.quantity || 1,
      unitPrice: this.itemData()?.unit_price || 0,
    });
  }

  onItemFormSubmit() {}
}

<ion-modal [trigger]="triggerId()">
  <ng-template>
    <ion-header>
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-button (click)="cancel()">Cancel</ion-button>
        </ion-buttons>
        <ion-title>Welcome</ion-title>
        <ion-buttons slot="end">
          <ion-button (click)="confirm()" [strong]="true">Confirm</ion-button>
        </ion-buttons>
      </ion-toolbar>
    </ion-header>
    <ion-content class="ion-padding">
      <form [formGroup]="itemForm" (ngSubmit)="onItemFormSubmit()">
        <ion-item>
          <ion-input
            type="text"
            label="Name"
            formControlName="name"
            [clearInput]="true"
          ></ion-input>
        </ion-item>
        <ion-item>
          <ion-input
            type="text"
            label="Description"
            formControlName="description"
            [clearInput]="true"
          >
          </ion-input>
        </ion-item>
        <ion-item>
          <ion-input
            type="number"
            label="Quantity"
            formControlName="quantity"
            [clearInput]="true"
          ></ion-input>
        </ion-item>
        <ion-item>
          <ion-input
            type="number"
            [label]="`Unit price ${currencyCode()}`"
            formControlName="unitPrice"
            [clearInput]="true"
          ></ion-input>
        </ion-item>
      </form>
    </ion-content>
  </ng-template>
</ion-modal>

// src/components/ItemEditModal.vue
<script setup lang="ts">
import {
  IonButton,
  IonButtons,
  IonContent,
  IonHeader,
  IonInput,
  IonItem,
  IonList,
  IonModal,
  IonTitle,
  IonToolbar,
} from "@ionic/vue";
import { computed, toRef } from "vue";

import { useReceipt } from "@/stores/receipt";
import { ReceiptItem } from "@/types/receipt.type";

const isItemEditModalOpen = defineModel<boolean>("open", {
  type: Boolean,
});

enum EditModeEnum {
  create = "create",
  edit = "edit",
}

const props = defineProps<{
  currency: string;
  item: ReceiptItem;
  mode: keyof typeof EditModeEnum;
}>();

const item = toRef(props.item);
const currency = toRef(props.currency);

const itemTotalPrice = computed(() => item.value.quantity * item.value.price);

const receiptStore = useReceipt();

const handleEditModalCancel = () => {
  isItemEditModalOpen.value = false;
};

const handleEditModalConfirm = () => {
  switch (props.mode) {
    case "create":
      addNewItem();
      break;
    case "edit":
      updateExistingItem();
      break;
    default:
      console.log("nothing to perform");
  }

  isItemEditModalOpen.value = false;
};

const updateExistingItem = () => {
  receiptStore.updateAnItem({
    ...item.value,
    price_total: itemTotalPrice.value,
  });
};

const addNewItem = () => {
  receiptStore.addNewItem({ ...item.value, price_total: itemTotalPrice.value });
};
</script>

<template>
  <ion-modal :is-open="isItemEditModalOpen">
    <ion-header>
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-button @click="handleEditModalCancel">Cancel</ion-button>
        </ion-buttons>
        <ion-title>{{
          props.mode === EditModeEnum.edit ? "Edit item" : "Create Item"
        }}</ion-title>
        <ion-buttons slot="end">
          <ion-button :strong="true" @click="handleEditModalConfirm"
            >Confirm</ion-button
          >
        </ion-buttons>
      </ion-toolbar>
    </ion-header>
    <ion-content>
      <ion-list>
        <ion-item>
          <ion-input type="text" label="Name" v-model="item.name"></ion-input>
        </ion-item>
        <ion-item>
          <ion-input
            type="number"
            label="Quantity"
            v-model="item.quantity"
          ></ion-input>
        </ion-item>
        <ion-item>
          <ion-input type="number" label="Unit price" v-model="item.price"
            ><span slot="end">{{ currency }}</span></ion-input
          >
        </ion-item>
        <ion-item>
          <ion-input
            type="number"
            label="Total price"
            :value="itemTotalPrice"
            disabled
            ><span slot="end">{{ currency }}</span></ion-input
          >
        </ion-item>
      </ion-list>
    </ion-content>
  </ion-modal>
</template>
